version: '2'
services:
  web:
    build: .
    command: bash -c "sleep 3 && rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - RAILS_ENV=mysql
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    links:
      - mysql
      - mailcatcher
  mysql:
    image: mysql:5.7.18
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - "1080:80"
      - "25:25"
